create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price numeric not null default 0 check (price >= 0),
  image_url text,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;

drop policy if exists "Allow public product read" on public.products;
drop policy if exists "Allow authenticated product insert" on public.products;
drop policy if exists "Allow authenticated product update" on public.products;
drop policy if exists "Allow authenticated product delete" on public.products;

create policy "Allow public product read"
on public.products
for select
to anon, authenticated
using (true);

create policy "Allow authenticated product insert"
on public.products
for insert
to authenticated
with check (true);

create policy "Allow authenticated product update"
on public.products
for update
to authenticated
using (true)
with check (true);

create policy "Allow authenticated product delete"
on public.products
for delete
to authenticated
using (true);
